import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Regenerates `packages/database/src/migration-manifest.ts` from the migration
 * folders — `pnpm db:manifest`.
 *
 * The manifest is what a running release compares with `_prisma_migrations`
 * before it reports ready (docs/RAILWAY-DEPLOYMENT.md §4.4). It is a checked-in
 * list rather than a directory read at runtime because the Next.js apps bundle
 * their server code: a path resolved from a module at build time is not
 * guaranteed to point at the migrations folder when the bundle runs, and a
 * readiness check that silently reads nothing would report ready for ever.
 *
 * `tests/unit/migration-manifest.test.ts` fails when a migration folder is added
 * without re-running this script, so the list cannot drift.
 */
const repoRoot = path.resolve(import.meta.dirname, '..');
const migrationsDir = path.join(repoRoot, 'packages/database/prisma/migrations');
const target = path.join(repoRoot, 'packages/database/src/migration-manifest.ts');

const names = readdirSync(migrationsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const body = `/**
 * GENERATED by \`pnpm db:manifest\` (scripts/write-migration-manifest.ts). Do not
 * edit by hand.
 *
 * Every migration this build was made with, in the order Prisma applies them.
 * A running release reports ready only when each of these is recorded as
 * finished in \`_prisma_migrations\` (see \`schema-readiness.ts\`).
 */
export const EXPECTED_MIGRATIONS: readonly string[] = [
${names.map((name) => `  '${name}',`).join('\n')}
];
`;

writeFileSync(target, body);
console.log(`wrote ${names.length} migrations to ${path.relative(repoRoot, target)}`);
