/**
 * Bring the PRODUCTION Platform Owner into existence, once.
 *
 * THIS IS NOT THE SEED, AND IT MUST NEVER BECOME IT. `prisma/seed.ts` builds a
 * development world: two workspaces, Sample Brand and North Star, customer
 * users, memberships, wallets, campaigns, content. Every one of those rows is
 * fiction, and fiction in a production database is indistinguishable from a
 * customer's real data the moment anybody looks at a table. So this command is
 * a separate file with a separate entry point, and the only rows it writes are:
 *
 *   - the permission catalogue the product defines,
 *   - the system roles the product defines,
 *   - ONE PlatformUser, the real owner, with the `platform_owner` role,
 *   - that owner's sealed TOTP seed and the hashes of their recovery codes,
 *   - the audit events recording all of the above.
 *
 * It writes no Workspace, no Brand, no customer User, no Membership, no wallet,
 * no campaign, no content, and nothing whose name contains "sample" or "demo".
 * `tests/isolation/bootstrap-production-owner.test.ts` counts those tables
 * before and after and fails if any of them moves.
 *
 * WHY IT REUSES EVERYTHING. The password is hashed by the same Argon2 code that
 * hashes a customer's. The TOTP enrolment is generated by the same function the
 * product uses. The seed is sealed by the same Secret Service, under the same
 * key domain, with the same audited actor. The roles are written through
 * `asPlatform`, which is the audited door production code uses. A bootstrap
 * with its own private crypto is a bootstrap whose accounts are only as good as
 * the crypto nobody reviewed.
 *
 * HOW TO RUN IT: docs/RAILWAY-DEPLOYMENT.md §24.
 */

import path from 'node:path';
import readline from 'node:readline';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  ALL_PERMISSIONS,
  ROLE_DEFINITIONS,
  assertRealmsAreDisjoint,
  assertRolePermissionsAreValid,
} from '@brandspace/shared';
import { asPlatform, assertPlatformRole } from '../src/platform';
import {
  BootstrapRefusal,
  assertBootstrapEnvironment,
  assertInteractiveDisclosure,
  assertUsableOwnerPassword,
  assertVaultCanSeal,
} from './bootstrap-owner-guards';

/**
 * The environment the sealed TOTP seed belongs to.
 *
 * FIXED, NOT DERIVED. This command refuses to run outside production, so there
 * is exactly one correct value — and reading it from configuration would create
 * a way for a mis-set variable to file the production owner's second factor
 * under `DEVELOPMENT`, where a development process could resolve it.
 */
const SECRET_ENVIRONMENT = 'PRODUCTION' as const;

/** What the command did, for the operator and for the tests. */
export type BootstrapOutcome =
  | { readonly kind: 'bootstrapped'; readonly platformUserId: string }
  | { readonly kind: 'already-bootstrapped'; readonly platformUserId: string }
  | { readonly kind: 'completed-partial'; readonly platformUserId: string };

/**
 * Material that must reach a human exactly once and then never again.
 *
 * Carried in a dedicated type rather than logged in passing, so that every
 * place it travels is visible in the signature. The only consumer is the
 * interactive disclosure at the end of `main`.
 */
export interface OneTimeEnrolment {
  readonly otpauthUri: string;
  readonly recoveryCodes: readonly string[];
}

export interface BootstrapResult {
  readonly outcome: BootstrapOutcome;
  /**
   * Present ONLY when this run performed the enrolment. A re-run against an
   * already-enrolled owner returns nothing here, because the seed it would have
   * to print is one it deliberately cannot read back.
   */
  readonly enrolment: OneTimeEnrolment | null;
}

export interface BootstrapDependencies {
  readonly prisma: PrismaClient;
  readonly ownerEmail: string;
  readonly password: string;
  /** Progress, never content. */
  readonly log: (line: string) => void;
}

/**
 * Synchronise the permission catalogue and the system roles.
 *
 * IDEMPOTENT BY CONSTRUCTION. Permissions upsert on their key; roles are found
 * by `(key, workspaceId: null)` and updated in place. Re-running changes
 * nothing except bringing a catalogue entry into line with the code, which is
 * what an operator wants after a deploy that added a permission.
 *
 * THE ROLE WRITE GOES THROUGH `asPlatform`, the audited cross-tenant door, for
 * the same reason the seed does: this is a platform operation, and a bootstrap
 * that wrote platform rows on a private connection would be the one place in
 * the system where a cross-tenant write left no evidence.
 */
async function syncCatalogue(
  prisma: PrismaClient,
  actorId: string,
  requestId: string,
  log: (line: string) => void,
): Promise<Map<string, string>> {
  for (const permission of ALL_PERMISSIONS) {
    await prisma.permission.upsert({
      where: { key: permission.key },
      update: {
        resource: permission.resource,
        action: permission.action,
        minScope: permission.minScope,
        description: permission.description,
      },
      create: {
        key: permission.key,
        resource: permission.resource,
        action: permission.action,
        minScope: permission.minScope,
        description: permission.description,
      },
    });
  }
  log(`  permission catalogue: ${ALL_PERMISSIONS.length} entries`);

  const roleIdsByKey = new Map<string, string>();
  await asPlatform(
    { platformUserId: actorId, roleKey: 'platform_owner', mfaVerified: true },
    {
      action: 'platform.bootstrap.roles',
      reason: 'Production bootstrap: synchronise system roles',
      requestId,
    },
    async (db) => {
      for (const definition of ROLE_DEFINITIONS) {
        const existing = await db.role.findFirst({
          where: { key: definition.key, workspaceId: null },
        });
        const role = existing
          ? await db.role.update({
              where: { id: existing.id },
              data: {
                nameEn: definition.nameEn,
                nameAr: definition.nameAr,
                realm: definition.realm === 'platform' ? 'PLATFORM' : 'WORKSPACE',
                isSystem: true,
              },
            })
          : await db.role.create({
              data: {
                key: definition.key,
                workspaceId: null,
                realm: definition.realm === 'platform' ? 'PLATFORM' : 'WORKSPACE',
                nameEn: definition.nameEn,
                nameAr: definition.nameAr,
                isSystem: true,
              },
            });
        roleIdsByKey.set(definition.key, role.id);

        await db.rolePermission.deleteMany({ where: { roleId: role.id } });
        for (const permissionKey of definition.permissionKeys) {
          const permission = await db.permission.findUnique({ where: { key: permissionKey } });
          if (!permission) throw new Error(`Unknown permission: ${permissionKey}`);
          await db.rolePermission.create({
            data: { roleId: role.id, permissionId: permission.id },
          });
        }
      }
    },
    /*
     * THE SAME CLIENT, not the platform pool.
     *
     * `asPlatform` opens its own pooled connection when it is given none, which
     * would mean this command talked to the database through two clients that
     * agree only because they read the same variable. One client, verified once
     * by `assertPlatformRole` below, is both simpler and stricter.
     *
     * NO `bootstrap: true`, unlike the seed. That flag skips `asPlatform`'s own
     * audit write, which is defensible when building a throwaway development
     * world and indefensible here: this is a cross-tenant write against the
     * production database, and it is exactly the kind of event the audit trail
     * exists to hold.
     */
    { prisma },
  );
  log(`  system roles: ${ROLE_DEFINITIONS.length} entries`);

  return roleIdsByKey;
}

/**
 * Stop if somebody else already owns this platform.
 *
 * WHY THIS IS A REFUSAL AND NOT A MERGE. A second `platform_owner` appearing
 * under a different address means one of two things: an operator typo, or
 * somebody else ran this command. Both deserve a human, and neither deserves a
 * script quietly adding a second full-privilege account to a live platform.
 *
 * THE EXISTING OWNER'S ADDRESS IS NOT PRINTED. Whoever is running this does not
 * necessarily have standing to learn who else administers the platform, and the
 * refusal is actionable without it: they can look in the Control Center, or ask
 * somebody who can.
 */
async function assertNoForeignOwner(prisma: PrismaClient, ownerEmail: string): Promise<void> {
  /*
   * THE ROLE IS LOOKED UP RATHER THAN PASSED IN, so that this can run BEFORE
   * the catalogue sync rather than after it. The refusal below ends with
   * "Nothing was written", and that sentence has to be true: an operator who
   * reads it must not have to wonder which half of the command already ran.
   *
   * No `platform_owner` role means no account can hold it, so there is nothing
   * to conflict with and the first run proceeds.
   */
  const ownerRole = await prisma.role.findFirst({
    where: { key: 'platform_owner', workspaceId: null },
    select: { id: true },
  });
  if (!ownerRole) return;

  const others = await prisma.platformUser.findMany({
    where: { roleId: ownerRole.id, email: { not: ownerEmail } },
    select: { id: true },
  });
  if (others.length > 0) {
    throw new BootstrapRefusal(
      `A different Platform Owner already exists (${others.length} account(s)). ` +
        'Refusing to add a second full-privilege account to a live platform. ' +
        'Their address is deliberately not printed. ' +
        'Resolve this in the Control Center, or re-run with the correct ' +
        'BOOTSTRAP_PLATFORM_OWNER_EMAIL. Nothing was written.',
    );
  }
}

/**
 * Create or complete the Platform Owner.
 *
 * "COMPLETE", NOT "REPLACE", and the distinction is the whole idempotency
 * story. A password hash that is already set is never overwritten; a TOTP seed
 * that is already sealed is never re-sealed; recovery codes that already exist
 * are never regenerated. Re-running this command against a finished owner
 * reports that and exits.
 *
 * What it WILL finish is a half-built account — the outcome of a command that
 * died between writing the user row and sealing the seed. Leaving that alone
 * would strand an owner who cannot complete MFA, and MFA is mandatory for
 * platform roles (D-27), so the account would be unusable and unfixable by any
 * other route.
 */
export async function bootstrapProductionOwner(
  deps: BootstrapDependencies,
): Promise<BootstrapResult> {
  const { prisma, ownerEmail, password, log } = deps;

  /*
   * WHO IS THIS CONNECTION, REALLY.
   *
   * Asked first, because every refusal after it assumes the answer. An
   * operator who pastes `DATABASE_URL` into `DATABASE_PLATFORM_URL` gets a
   * connection that works — it just cannot see platform rows — and the failure
   * would surface as a confusing permission error somewhere in the middle of
   * the catalogue sync. This is the same check the platform pool makes on its
   * own first use; the bootstrap builds its client by hand, so it makes the
   * check by hand too.
   */
  await assertPlatformRole(prisma);

  // Refuse a nonsensical role/permission model before touching a row.
  assertRealmsAreDisjoint();
  assertRolePermissionsAreValid();

  assertUsableOwnerPassword(password);

  const requestId = `bootstrap-${crypto.randomUUID()}`;

  /*
   * THE ACTOR IS THE OWNER BEING CREATED. On a first run the account does not
   * exist yet, so its id is minted here and used both as the audited actor and
   * as the row's primary key. The alternative — a synthetic system actor — puts
   * an id in the audit trail that corresponds to nobody.
   */
  const existingOwner = await prisma.platformUser.findUnique({ where: { email: ownerEmail } });
  const platformUserId = existingOwner?.id ?? crypto.randomUUID();

  await assertNoForeignOwner(prisma, ownerEmail);

  const roleIdsByKey = await syncCatalogue(prisma, platformUserId, requestId, log);
  const ownerRoleId = roleIdsByKey.get('platform_owner');
  if (!ownerRoleId) throw new Error('platform_owner role was not created.');

  const { hashPassword, generateTotpEnrolment, generateRecoveryCodes, PlatformAuthService } =
    await import('@brandspace/auth');
  const { SecretService, buildSecretRef } = await import('@brandspace/secrets');

  const mfaRef = buildSecretRef({
    category: 'mfa_totp',
    provider: 'platform',
    environment: 'production',
    name: ownerEmail,
  });

  const sealedSeed = await prisma.secretRecord.findUnique({
    where: { ref_environment: { ref: mfaRef, environment: SECRET_ENVIRONMENT } },
  });

  const alreadyComplete =
    existingOwner !== null &&
    existingOwner.passwordHash !== null &&
    existingOwner.mfaEnabled &&
    existingOwner.mfaSecretRef !== null &&
    sealedSeed !== null;

  if (alreadyComplete) {
    /*
     * NOTHING IS TOUCHED, AND NOTHING IS DISCLOSED. The seed cannot be shown
     * again — the Secret Service seals it and this command has no business
     * unsealing one. An owner who has lost their authenticator recovers with a
     * recovery code, not by re-running a bootstrap.
     */
    log('  Platform Owner is already fully bootstrapped. Nothing was changed.');
    return { outcome: { kind: 'already-bootstrapped', platformUserId }, enrolment: null };
  }

  const owner = await prisma.platformUser.upsert({
    where: { email: ownerEmail },
    // The ROLE is the only thing a re-run re-asserts, so a catalogue change that
    // minted a new role id cannot orphan the owner. The password hash, the MFA
    // flag and the seed reference are deliberately absent from this update.
    update: { roleId: ownerRoleId },
    create: {
      id: platformUserId,
      email: ownerEmail,
      name: 'Platform Owner',
      status: 'ACTIVE',
      mfaEnabled: false,
      passwordHash: null,
      roleId: ownerRoleId,
    },
  });

  let enrolment: OneTimeEnrolment | null = null;

  if (sealedSeed === null || owner.mfaSecretRef === null || !owner.mfaEnabled) {
    const generated = generateTotpEnrolment(ownerEmail);

    /*
     * READ BACK FROM THE DATABASE, not taken from the constant.
     *
     * `SecretService` refuses a write unless the actor carries
     * `platform.secret.manage`, and the actor here is the owner being created.
     * Asserting the permissions from `ROLE_DEFINITIONS` would describe what the
     * role SHOULD have; reading `role_permission` describes what it DOES have.
     * If the catalogue sync above silently failed to attach a permission, this
     * refuses rather than sealing a seed for a role that cannot manage secrets.
     */
    const ownerPermissionKeys = (
      await prisma.rolePermission.findMany({
        where: { roleId: ownerRoleId },
        include: { permission: true },
      })
    ).map((row) => row.permission.key);

    /*
     * SEALED BEFORE IT IS REFERENCED. If the write fails, the owner row still
     * says `mfaEnabled: false` and the next run enrols cleanly. The reverse
     * order would leave a user pointing at a seed that does not exist.
     */
    await new SecretService({ prisma }).createSecret(
      {
        platformUserId: owner.id,
        roleKey: 'platform_owner',
        mfaVerified: true,
        permissionKeys: ownerPermissionKeys,
      },
      {
        ref: mfaRef,
        name: `TOTP seed for ${ownerEmail}`,
        category: 'mfa_totp',
        environment: SECRET_ENVIRONMENT,
        value: generated.secret,
      },
    );

    const recoveryCodes = generateRecoveryCodes();
    await new PlatformAuthService({ prisma }).storeRecoveryCodes(owner.id, recoveryCodes);

    await prisma.platformUser.update({
      where: { id: owner.id },
      data: { mfaEnabled: true, mfaSecretRef: mfaRef, mfaEnrolledAt: new Date() },
    });

    enrolment = { otpauthUri: generated.otpauthUri, recoveryCodes };
    log('  MFA enrolled, seed sealed through the Secret Service.');
  } else {
    log('  MFA was already enrolled; the existing seed was left untouched.');
  }

  if (owner.passwordHash === null) {
    await prisma.platformUser.update({
      where: { id: owner.id },
      data: { passwordHash: await hashPassword(password) },
    });
    log('  Password set (Argon2id, never printed).');
  } else {
    /*
     * A PASSWORD THAT EXISTS IS NEVER REPLACED. Re-running this command is not
     * a password reset, and treating it as one would make a bootstrap script a
     * standing account-takeover primitive for anybody who can reach a shell.
     */
    log('  Password was already set; it was left untouched.');
  }

  await prisma.auditEvent.create({
    data: {
      workspaceId: null,
      // PLATFORM_USER, not SYSTEM: a person ran this, and the account they
      // created is the one the trail should name.
      actorType: 'PLATFORM_USER',
      actorId: owner.id,
      action: 'platform.bootstrap.owner',
      resourceType: 'platform_user',
      resourceId: owner.id,
      severity: 'CRITICAL',
      outcome: 'SUCCESS',
      // The ADDRESS is the identity of the account and belongs in the trail.
      // The password, the seed and the recovery codes do not, and are absent.
      reason: `Production Platform Owner bootstrap for ${ownerEmail}`,
    },
  });

  return {
    outcome: {
      kind: existingOwner === null ? 'bootstrapped' : 'completed-partial',
      platformUserId: owner.id,
    },
    enrolment,
  };
}

// ---------------------------------------------------------------------------
// The command
// ---------------------------------------------------------------------------

/**
 * Read a secret from the terminal without echoing it.
 *
 * `readline` writes every keystroke back to the output by default, which is
 * what makes a typed password appear. Replacing `_writeToOutput` while the
 * prompt is live suppresses that, so the value never reaches the screen and
 * therefore never reaches the scrollback an operator might later paste.
 */
function readSecretFromTty(promptText: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: true,
    });
    const muted = { on: false };
    const target = rl as unknown as { _writeToOutput: (chunk: string) => void };
    target._writeToOutput = (chunk: string) => {
      if (!muted.on) process.stdout.write(chunk);
    };

    process.stdout.write(promptText);
    muted.on = true;
    rl.question('', (answer) => {
      muted.on = false;
      process.stdout.write('\n');
      rl.close();
      resolve(answer);
    });
  });
}

/**
 * Where the password comes from.
 *
 * THE TERMINAL IS THE ONLY GOOD ANSWER. A typed password exists in the
 * operator's head and in this process; an exported one exists in the shell's
 * history, in `/proc`, and in whatever captured the session.
 *
 * `BOOTSTRAP_PLATFORM_OWNER_PASSWORD` is supported for the case where a
 * terminal genuinely cannot prompt, and it is deliberately PROCESS-LOCAL: it is
 * meant to be set inline for one command, never added to Railway's variables,
 * where it would sit readable by anybody with project access for as long as
 * nobody thought to remove it. The banner says so every time it is used.
 */
async function resolvePassword(log: (line: string) => void): Promise<string> {
  const fromEnvironment = process.env['BOOTSTRAP_PLATFORM_OWNER_PASSWORD'];
  if (fromEnvironment !== undefined && fromEnvironment !== '') {
    log('  Password taken from BOOTSTRAP_PLATFORM_OWNER_PASSWORD (process-local).');
    log('  If that variable is stored in Railway rather than typed inline, REMOVE IT NOW.');
    return fromEnvironment;
  }

  const first = await readSecretFromTty('  New Platform Owner password (not echoed): ');
  const second = await readSecretFromTty('  Confirm it: ');
  if (first !== second) {
    throw new BootstrapRefusal('The two passwords did not match. Nothing was written.');
  }
  return first;
}

function client(): PrismaClient {
  /*
   * THE PLATFORM ROLE, and only it. The permission catalogue, the system roles
   * and `platform_user` are platform-owned tables that the tenant role has no
   * privilege on — and `FORCE ROW LEVEL SECURITY` means even the schema owner
   * is subject to policy. This command gets no private door.
   */
  const connectionString = process.env['DATABASE_PLATFORM_URL'];
  /* c8 ignore next -- the guard already refused an absent value. */
  if (!connectionString) throw new BootstrapRefusal('DATABASE_PLATFORM_URL is not set.');
  return new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
}

async function main(): Promise<void> {
  const log = (line: string): void => console.log(line);

  // Order matters: environment first, so a wrong deployment is refused before a
  // password is ever requested; TTY second, so an operator in a pipe is stopped
  // before the enrolment that could not be shown to them is generated.
  const { ownerEmail } = assertBootstrapEnvironment(process.env);
  /*
   * THE VAULT, BEFORE THE TERMINAL. Sealing the seed is the step that cannot be
   * undone halfway, so its precondition is checked before anything else is even
   * asked for.
   */
  assertVaultCanSeal(process.env);
  assertInteractiveDisclosure(process.stdout.isTTY === true, process.stdin.isTTY === true);

  log('BrandSpace — production Platform Owner bootstrap');
  log(`  Owner address: ${ownerEmail}`);
  log('  This creates NO workspace, brand, customer or sample data.');
  log('');

  const password = await resolvePassword(log);
  const prisma = client();

  try {
    const { outcome, enrolment } = await bootstrapProductionOwner({
      prisma,
      ownerEmail,
      password,
      log,
    });

    log('');
    if (outcome.kind === 'already-bootstrapped') {
      log('✔ Already bootstrapped. No row was created, changed or replaced.');
      return;
    }

    log(
      outcome.kind === 'bootstrapped' ? '✔ Platform Owner created.' : '✔ Platform Owner completed.',
    );

    if (enrolment) {
      /*
       * THE ONE-TIME DISCLOSURE. Shown here and nowhere else, to a terminal the
       * guard above has already established is real. Nothing on these lines is
       * recoverable from the database afterwards: the seed is sealed and the
       * recovery codes are stored as hashes.
       */
      log('');
      log('  ── SHOWN ONCE. Nothing below can be recovered. ──────────────────────');
      log(`  otpauth URI    : ${enrolment.otpauthUri}`);
      log(`  recovery codes : ${enrolment.recoveryCodes.join(' ')}`);
      log('  ─────────────────────────────────────────────────────────────────────');
      log('  Scan the URI into an authenticator NOW and store the recovery codes in');
      log('  a password manager. Then clear this terminal’s scrollback.');
    }
  } finally {
    await prisma.$disconnect();
  }
}

/*
 * RUN ONLY WHEN EXECUTED DIRECTLY. The tests import `bootstrapProductionOwner`
 * and the guards; importing this module must not start prompting for a
 * password on a test runner's stdin.
 */
const executedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]).startsWith(path.resolve(import.meta.dirname));

if (executedDirectly) {
  main().catch((error: unknown) => {
    // The message, never the stack: a stack from this file names arguments.
    const message = error instanceof Error ? error.message : 'Bootstrap failed.';
    console.error(`\n✖ ${message}`);
    process.exitCode = 1;
  });
}
