/**
 * Bring the PRODUCTION Platform Owner into existence, once.
 *
 * THIS IS NOT THE SEED, AND IT MUST NEVER BECOME IT. `prisma/seed.ts` builds a
 * development world: two workspaces, Sample Brand and North Star, customer
 * users, memberships, wallets, campaigns, content. Every one of those rows is
 * fiction, and fiction in a production database is indistinguishable from a
 * customer's real data the moment anybody looks at a table. So this command is
 * a separate file with a separate entry point, and the only rows it writes are:
 *
 *   - the permission catalogue the product defines,
 *   - the system roles the product defines,
 *   - ONE PlatformUser, the real owner, with the `platform_owner` role,
 *   - that owner's sealed TOTP seed and the hashes of their recovery codes,
 *   - the audit events recording all of the above — one per run that did
 *     something, and none at all from a run that found nothing to do.
 *
 * It writes no Workspace, no Brand, no customer User, no Membership, no wallet,
 * no campaign, no content, and nothing whose name contains "sample" or "demo".
 * `tests/isolation/bootstrap-production-owner.test.ts` counts those tables
 * before and after and fails if any of them moves.
 *
 * WHY IT REUSES EVERYTHING. The password is hashed by the same Argon2 code that
 * hashes a customer's. The TOTP enrolment is generated by the same function the
 * product uses. The seed is sealed by the same Secret Service, under the same
 * key domain, with the same audited actor. The roles are written through
 * `asPlatform`, which is the audited door production code uses. A bootstrap
 * with its own private crypto is a bootstrap whose accounts are only as good as
 * the crypto nobody reviewed.
 *
 * AND ENROLMENT IS FINISHED BY A PERSON, NOT BY THIS SCRIPT. Generating a seed
 * proves nothing: not that the operator scanned it, not that their
 * authenticator accepted it, not that the two clocks agree. So MFA stays off
 * and no recovery codes exist until a live six-digit code, read off that
 * authenticator, verifies against the seed just sealed. `classifyOwner` in
 * `bootstrap-owner-guards.ts` enumerates every state the account can be left
 * in — including the one a wrong code produces — and says which are resumable
 * and which get a human instead.
 *
 * HOW TO RUN IT: docs/RAILWAY-DEPLOYMENT.md §24.
 */

import path from 'node:path';
import readline from 'node:readline';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  ALL_PERMISSIONS,
  ROLE_DEFINITIONS,
  assertRealmsAreDisjoint,
  assertRolePermissionsAreValid,
} from '@brandspace/shared';
import { asPlatform, assertPlatformRole } from '../src/platform';
import {
  BootstrapRefusal,
  assertBootstrapEnvironment,
  assertInteractiveDisclosure,
  assertUsableOwnerPassword,
  assertVaultCanSeal,
  classifyOwner,
} from './bootstrap-owner-guards';

/**
 * The environment the sealed TOTP seed belongs to.
 *
 * FIXED, NOT DERIVED. This command refuses to run outside production, so there
 * is exactly one correct value — and reading it from configuration would create
 * a way for a mis-set variable to file the production owner's second factor
 * under `DEVELOPMENT`, where a development process could resolve it.
 */
const SECRET_ENVIRONMENT = 'PRODUCTION' as const;

/** What the command did, for the operator and for the tests. */
export type BootstrapOutcome =
  /** An empty database: the account was created and enrolled. */
  | { readonly kind: 'bootstrapped'; readonly platformUserId: string }
  /** An enrolment that had been sealed and never confirmed was finished. */
  | { readonly kind: 'resumed'; readonly platformUserId: string }
  /** MFA was already complete; only the missing password was set. */
  | { readonly kind: 'completed-partial'; readonly platformUserId: string }
  /** Nothing to do, and nothing done. */
  | { readonly kind: 'already-bootstrapped'; readonly platformUserId: string };

/**
 * What the operator is shown, and what they must send back.
 *
 * A NARROW TYPE ON PURPOSE. The seed itself never leaves
 * `bootstrapProductionOwner`; what crosses this boundary is the URI an
 * authenticator scans, and what comes back is six digits. Anything that wanted
 * the raw secret would have to change this signature, which is exactly the
 * kind of change that should be hard to make by accident.
 */
export interface EnrolmentChallenge {
  readonly otpauthUri: string;
}

export interface BootstrapResult {
  readonly outcome: BootstrapOutcome;
  /**
   * Plaintext recovery codes, to be shown exactly once.
   *
   * Present ONLY when this run completed an enrolment. A re-run against a
   * finished owner returns nothing here — the codes it would have to print are
   * stored as hashes and cannot be recovered, which is the point of storing
   * them that way.
   */
  readonly recoveryCodes: readonly string[] | null;
}

export interface BootstrapDependencies {
  readonly prisma: PrismaClient;
  readonly ownerEmail: string;
  readonly password: string;
  /** Progress, never content. */
  readonly log: (line: string) => void;
  /**
   * Show the enrolment to a person and read back a live code from their
   * authenticator. The account is not enrolled until what this returns
   * verifies.
   */
  readonly confirmEnrolment: (challenge: EnrolmentChallenge) => Promise<string>;
}

/**
 * Synchronise the permission catalogue and the system roles.
 *
 * IDEMPOTENT BY CONSTRUCTION. Permissions upsert on their key; roles are found
 * by `(key, workspaceId: null)` and updated in place. Re-running changes
 * nothing except bringing a catalogue entry into line with the code, which is
 * what an operator wants after a deploy that added a permission.
 *
 * THE ROLE WRITE GOES THROUGH `asPlatform`, the audited cross-tenant door, for
 * the same reason the seed does: this is a platform operation, and a bootstrap
 * that wrote platform rows on a private connection would be the one place in
 * the system where a cross-tenant write left no evidence.
 */
async function syncCatalogue(
  prisma: PrismaClient,
  actorId: string,
  requestId: string,
  log: (line: string) => void,
): Promise<Map<string, string>> {
  for (const permission of ALL_PERMISSIONS) {
    await prisma.permission.upsert({
      where: { key: permission.key },
      update: {
        resource: permission.resource,
        action: permission.action,
        minScope: permission.minScope,
        description: permission.description,
      },
      create: {
        key: permission.key,
        resource: permission.resource,
        action: permission.action,
        minScope: permission.minScope,
        description: permission.description,
      },
    });
  }
  log(`  permission catalogue: ${ALL_PERMISSIONS.length} entries`);

  const roleIdsByKey = new Map<string, string>();
  await asPlatform(
    { platformUserId: actorId, roleKey: 'platform_owner', mfaVerified: true },
    {
      action: 'platform.bootstrap.roles',
      reason: 'Production bootstrap: synchronise system roles',
      requestId,
    },
    async (db) => {
      for (const definition of ROLE_DEFINITIONS) {
        const existing = await db.role.findFirst({
          where: { key: definition.key, workspaceId: null },
        });
        const role = existing
          ? await db.role.update({
              where: { id: existing.id },
              data: {
                nameEn: definition.nameEn,
                nameAr: definition.nameAr,
                realm: definition.realm === 'platform' ? 'PLATFORM' : 'WORKSPACE',
                isSystem: true,
              },
            })
          : await db.role.create({
              data: {
                key: definition.key,
                workspaceId: null,
                realm: definition.realm === 'platform' ? 'PLATFORM' : 'WORKSPACE',
                nameEn: definition.nameEn,
                nameAr: definition.nameAr,
                isSystem: true,
              },
            });
        roleIdsByKey.set(definition.key, role.id);

        await db.rolePermission.deleteMany({ where: { roleId: role.id } });
        for (const permissionKey of definition.permissionKeys) {
          const permission = await db.permission.findUnique({ where: { key: permissionKey } });
          if (!permission) throw new Error(`Unknown permission: ${permissionKey}`);
          await db.rolePermission.create({
            data: { roleId: role.id, permissionId: permission.id },
          });
        }
      }
    },
    /*
     * THE SAME CLIENT, not the platform pool.
     *
     * `asPlatform` opens its own pooled connection when it is given none, which
     * would mean this command talked to the database through two clients that
     * agree only because they read the same variable. One client, verified once
     * by `assertPlatformRole` below, is both simpler and stricter.
     *
     * NO `bootstrap: true`, unlike the seed. That flag skips `asPlatform`'s own
     * audit write, which is defensible when building a throwaway development
     * world and indefensible here: this is a cross-tenant write against the
     * production database, and it is exactly the kind of event the audit trail
     * exists to hold.
     */
    { prisma },
  );
  log(`  system roles: ${ROLE_DEFINITIONS.length} entries`);

  return roleIdsByKey;
}

/**
 * Stop if somebody else already owns this platform.
 *
 * WHY THIS IS A REFUSAL AND NOT A MERGE. A second `platform_owner` appearing
 * under a different address means one of two things: an operator typo, or
 * somebody else ran this command. Both deserve a human, and neither deserves a
 * script quietly adding a second full-privilege account to a live platform.
 *
 * THE EXISTING OWNER'S ADDRESS IS NOT PRINTED. Whoever is running this does not
 * necessarily have standing to learn who else administers the platform, and the
 * refusal is actionable without it: they can look in the Control Center, or ask
 * somebody who can.
 */
async function assertNoForeignOwner(prisma: PrismaClient, ownerEmail: string): Promise<void> {
  /*
   * THE ROLE IS LOOKED UP RATHER THAN PASSED IN, so that this can run BEFORE
   * the catalogue sync rather than after it. The refusal below ends with
   * "Nothing was written", and that sentence has to be true: an operator who
   * reads it must not have to wonder which half of the command already ran.
   *
   * No `platform_owner` role means no account can hold it, so there is nothing
   * to conflict with and the first run proceeds.
   */
  const ownerRole = await prisma.role.findFirst({
    where: { key: 'platform_owner', workspaceId: null },
    select: { id: true },
  });
  if (!ownerRole) return;

  const others = await prisma.platformUser.findMany({
    where: { roleId: ownerRole.id, email: { not: ownerEmail } },
    select: { id: true },
  });
  if (others.length > 0) {
    throw new BootstrapRefusal(
      `A different Platform Owner already exists (${others.length} account(s)). ` +
        'Refusing to add a second full-privilege account to a live platform. ' +
        'Their address is deliberately not printed. ' +
        'Resolve this in the Control Center, or re-run with the correct ' +
        'BOOTSTRAP_PLATFORM_OWNER_EMAIL. Nothing was written.',
    );
  }
}

/**
 * Create or complete the Platform Owner.
 *
 * "COMPLETE", NOT "REPLACE", and the distinction is the whole idempotency
 * story. A password hash that is already set is never overwritten; a TOTP seed
 * that is already sealed is never re-sealed; recovery codes that already exist
 * are never regenerated. Re-running this command against a finished owner
 * reports that and exits.
 *
 * What it WILL finish is a half-built account — the outcome of a command that
 * died between writing the user row and sealing the seed. Leaving that alone
 * would strand an owner who cannot complete MFA, and MFA is mandatory for
 * platform roles (D-27), so the account would be unusable and unfixable by any
 * other route.
 */
export async function bootstrapProductionOwner(
  deps: BootstrapDependencies,
): Promise<BootstrapResult> {
  const { prisma, ownerEmail, password, log, confirmEnrolment } = deps;

  /*
   * WHO IS THIS CONNECTION, REALLY.
   *
   * Asked first, because every refusal after it assumes the answer. An
   * operator who pastes `DATABASE_URL` into `DATABASE_PLATFORM_URL` gets a
   * connection that works — it just cannot see platform rows — and the failure
   * would surface as a confusing permission error somewhere in the middle of
   * the catalogue sync. This is the same check the platform pool makes on its
   * own first use; the bootstrap builds its client by hand, so it makes the
   * check by hand too.
   */
  await assertPlatformRole(prisma);

  // Refuse a nonsensical role/permission model before touching a row.
  assertRealmsAreDisjoint();
  assertRolePermissionsAreValid();

  assertUsableOwnerPassword(password);

  const { buildSecretRef, SecretService } = await import('@brandspace/secrets');
  const mfaRef = buildSecretRef({
    category: 'mfa_totp',
    provider: 'platform',
    environment: 'production',
    name: ownerEmail,
  });

  await assertNoForeignOwner(prisma, ownerEmail);

  /*
   * READ, CLASSIFY, AND ONLY THEN WRITE.
   *
   * THE ORDER IS THE WHOLE CORRECTION. The first version synchronised the
   * catalogue and wrote an audit event BEFORE asking whether there was
   * anything to do, so "already bootstrapped, nothing changed" was not true:
   * roles were rewritten and the trail grew on every invocation. Now the
   * completed case returns having written nothing at all, and the sentence
   * the operator reads is one they can rely on.
   */
  const existingOwner = await prisma.platformUser.findUnique({ where: { email: ownerEmail } });
  const sealedSeed = await prisma.secretRecord.findUnique({
    where: { ref_environment: { ref: mfaRef, environment: SECRET_ENVIRONMENT } },
    select: { id: true, status: true },
  });

  const state = classifyOwner({ owner: existingOwner, sealed: sealedSeed, expectedRef: mfaRef });

  if (state.kind === 'inconsistent') {
    /*
     * FAIL CLOSED. Every state that reaches here is one this command did not
     * produce and cannot repair without guessing which half of it is correct —
     * and the wrong guess replaces a working second factor. Nothing was
     * written; a person decides.
     */
    throw new BootstrapRefusal(
      `Refusing to bootstrap: ${state.reason}\n` +
        'Nothing was written. Resolve this in the Control Center, or with somebody who can.',
    );
  }

  if (state.kind === 'complete') {
    /* c8 ignore next -- `complete` is only ever returned for an existing owner. */
    if (existingOwner === null) throw new Error('classifyOwner reported complete with no owner.');
    /*
     * INERT, AND LITERALLY SO. No role is rewritten, no permission upserted, no
     * audit event appended — this path performs two SELECTs and returns.
     *
     * NOTHING IS DISCLOSED EITHER. The seed cannot be shown again: it is sealed,
     * and this command has no business unsealing one. An owner who has lost
     * their authenticator recovers with a recovery code, not by re-running a
     * bootstrap.
     */
    log('  Platform Owner is already fully bootstrapped.');
    log('  Nothing was written: no role, no permission, no audit event, no secret.');
    return {
      outcome: { kind: 'already-bootstrapped', platformUserId: existingOwner.id },
      recoveryCodes: null,
    };
  }

  const requestId = `bootstrap-${crypto.randomUUID()}`;

  /*
   * THE ACTOR IS THE OWNER BEING CREATED. On a first run the account does not
   * exist yet, so its id is minted here and used both as the audited actor and
   * as the row's primary key. The alternative — a synthetic system actor — puts
   * an id in the audit trail that corresponds to nobody.
   */
  const platformUserId = existingOwner?.id ?? crypto.randomUUID();

  const roleIdsByKey = await syncCatalogue(prisma, platformUserId, requestId, log);
  const ownerRoleId = roleIdsByKey.get('platform_owner');
  if (!ownerRoleId) throw new Error('platform_owner role was not created.');

  const owner = await prisma.platformUser.upsert({
    where: { email: ownerEmail },
    // The ROLE is the only thing a re-run re-asserts, so a catalogue change that
    // minted a new role id cannot orphan the owner. The password hash, the MFA
    // flag and the seed reference are deliberately absent from this update.
    update: { roleId: ownerRoleId },
    create: {
      id: platformUserId,
      email: ownerEmail,
      name: 'Platform Owner',
      status: 'ACTIVE',
      mfaEnabled: false,
      passwordHash: null,
      roleId: ownerRoleId,
    },
  });

  const {
    hashPassword,
    generateTotpEnrolment,
    generateRecoveryCodes,
    totpVerifier,
    PlatformAuthService,
  } = await import('@brandspace/auth');

  if (state.kind === 'needs-password') {
    /*
     * MFA IS ALREADY COMPLETE AND IS NOT TOUCHED. Setting a password that was
     * never set is not a reset, and it is the one thing that stands between
     * this account and being usable.
     */
    await prisma.platformUser.update({
      where: { id: owner.id },
      data: { passwordHash: await hashPassword(password) },
    });
    log('  Password set (Argon2id, never printed). The existing MFA enrolment was not touched.');
    await recordBootstrap(prisma, owner.id, ownerEmail, 'password completed for an enrolled owner');
    return {
      outcome: { kind: 'completed-partial', platformUserId: owner.id },
      recoveryCodes: null,
    };
  }

  // --- Enrolment, which is not finished until a person proves it works ------

  const generated = generateTotpEnrolment(ownerEmail);

  /*
   * PERMISSIONS READ BACK FROM THE DATABASE, not taken from the constant.
   *
   * `SecretService` refuses a write unless the actor carries
   * `platform.secret.manage`, and the actor here is the owner being created.
   * Asserting the permissions from `ROLE_DEFINITIONS` would describe what the
   * role SHOULD have; reading `role_permission` describes what it DOES have.
   * If the catalogue sync above silently failed to attach a permission, this
   * refuses rather than sealing a seed for a role that cannot manage secrets.
   */
  const actor = {
    platformUserId: owner.id,
    roleKey: 'platform_owner',
    mfaVerified: true,
    permissionKeys: (
      await prisma.rolePermission.findMany({
        where: { roleId: ownerRoleId },
        include: { permission: true },
      })
    ).map((row) => row.permission.key),
  };

  const secrets = new SecretService({ prisma });

  if (state.kind === 'enrolment-pending') {
    /*
     * ROTATE, NEVER RE-CREATE — AND NEVER REVEAL.
     *
     * THIS IS THE DEFECT THIS REWRITE EXISTS TO FIX. A seed sealed under this
     * ref with MFA still switched off is what a crash, or a mistyped
     * confirmation code, leaves behind. The previous version took the enrolment
     * branch anyway and called `createSecret` for a ref that already existed,
     * which conflicts on the unique index — so the only command able to finish
     * a half-finished account was the one command guaranteed to fail on it.
     *
     * Rotating writes a NEW version of the same record, which is why it cannot
     * conflict. And rotating is the right answer rather than merely the
     * convenient one: the old seed was never activated, so nobody's
     * authenticator depends on it, and replacing it means this command never
     * has to unseal and print a stored secret.
     */
    await secrets.rotateSecret(
      actor,
      state.secretId,
      generated.secret,
      'Production bootstrap: resuming an enrolment that was never confirmed',
    );
    log('  An unconfirmed enrolment was found. Its seed was ROTATED, not revealed.');
  } else {
    /*
     * SEALED BEFORE IT IS REFERENCED. If this write fails, the owner row still
     * says `mfaEnabled: false` and the next run resumes cleanly. The reverse
     * order would leave a user pointing at a seed that does not exist.
     */
    await secrets.createSecret(actor, {
      ref: mfaRef,
      name: `TOTP seed for ${ownerEmail}`,
      category: 'mfa_totp',
      environment: SECRET_ENVIRONMENT,
      value: generated.secret,
    });
    log('  Seed sealed through the Secret Service.');
  }

  /*
   * MFA IS STILL OFF AT THIS POINT, AND THAT IS THE POINT.
   *
   * Generating a seed proves nothing. It does not prove the operator scanned
   * it, that their authenticator accepted it, or that the two clocks agree.
   * An account marked `mfaEnabled` on the strength of a seed nobody has used
   * is an account whose owner discovers at their first sign-in that they
   * cannot get in — and mandatory platform MFA (D-27) means there is no other
   * door.
   *
   * So the switch is thrown by a code read off a real authenticator, and by
   * nothing else.
   */
  const code = await confirmEnrolment({ otpauthUri: generated.otpauthUri });

  if (!totpVerifier.verify({ secret: generated.secret, token: code })) {
    /*
     * The seed stays sealed and MFA stays off, which is exactly the
     * `enrolment-pending` state the next run knows how to resume. No recovery
     * codes were generated, so none were invalidated.
     */
    throw new BootstrapRefusal(
      'That code did not verify.\n' +
        'MFA was NOT enabled and no recovery codes were issued.\n' +
        'The seed remains sealed and unconfirmed; re-run this command to enrol again — it will\n' +
        'rotate that seed and show you a fresh one. Check that the authenticator holds the entry\n' +
        'you just scanned, and that this machine’s clock is correct.',
    );
  }

  const recoveryCodes = generateRecoveryCodes();

  /*
   * CODES FIRST, THEN THE SWITCH.
   *
   * `storeRecoveryCodes` REPLACES the whole set, and enabling MFA is the write
   * that makes the account real. In this order, a crash between the two leaves
   * codes stored against an account whose MFA is still off — which classifies
   * as `enrolment-pending`, and the next run replaces them. The reverse order
   * would leave an ENABLED account with no recovery codes, which is one lost
   * phone away from permanent lockout.
   */
  await new PlatformAuthService({ prisma }).storeRecoveryCodes(owner.id, recoveryCodes);

  const enrolledAt = new Date();
  await prisma.platformUser.update({
    where: { id: owner.id },
    data:
      owner.passwordHash === null
        ? {
            mfaEnabled: true,
            mfaSecretRef: mfaRef,
            mfaEnrolledAt: enrolledAt,
            passwordHash: await hashPassword(password),
          }
        : {
            /*
             * A PASSWORD THAT EXISTS IS NEVER REPLACED. Re-running this command
             * is not a password reset, and treating it as one would make a
             * bootstrap script a standing account-takeover primitive for
             * anybody who can reach a shell.
             */
            mfaEnabled: true,
            mfaSecretRef: mfaRef,
            mfaEnrolledAt: enrolledAt,
          },
  });
  log('  Code verified. MFA enabled, recovery codes stored as hashes.');

  await recordBootstrap(
    prisma,
    owner.id,
    ownerEmail,
    existingOwner === null ? 'owner created and enrolled' : 'unconfirmed enrolment resumed',
  );

  return {
    outcome: {
      kind: existingOwner === null ? 'bootstrapped' : 'resumed',
      platformUserId: owner.id,
    },
    recoveryCodes,
  };
}

/**
 * The one audit event this command writes per effective run.
 *
 * NOT WRITTEN AT ALL when there was nothing to do: an audit trail that records
 * a no-op as an action is one more thing a future reader has to discount.
 */
async function recordBootstrap(
  prisma: PrismaClient,
  ownerId: string,
  ownerEmail: string,
  what: string,
): Promise<void> {
  await prisma.auditEvent.create({
    data: {
      workspaceId: null,
      // PLATFORM_USER, not SYSTEM: a person ran this, and the account they
      // created is the one the trail should name.
      actorType: 'PLATFORM_USER',
      actorId: ownerId,
      action: 'platform.bootstrap.owner',
      resourceType: 'platform_user',
      resourceId: ownerId,
      severity: 'CRITICAL',
      outcome: 'SUCCESS',
      // The ADDRESS is the identity of the account and belongs in the trail.
      // The password, the seed and the recovery codes do not, and are absent.
      reason: `Production Platform Owner bootstrap for ${ownerEmail}: ${what}`,
    },
  });
}

// ---------------------------------------------------------------------------
// The command
// ---------------------------------------------------------------------------

/**
 * Read a secret from the terminal without echoing it.
 *
 * `readline` writes every keystroke back to the output by default, which is
 * what makes a typed password appear. Replacing `_writeToOutput` while the
 * prompt is live suppresses that, so the value never reaches the screen and
 * therefore never reaches the scrollback an operator might later paste.
 */
function readSecretFromTty(promptText: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: true,
    });
    const muted = { on: false };
    const target = rl as unknown as { _writeToOutput: (chunk: string) => void };
    target._writeToOutput = (chunk: string) => {
      if (!muted.on) process.stdout.write(chunk);
    };

    process.stdout.write(promptText);
    muted.on = true;
    rl.question('', (answer) => {
      muted.on = false;
      process.stdout.write('\n');
      rl.close();
      resolve(answer);
    });
  });
}

/**
 * Read one line from the terminal, echoed.
 *
 * DELIBERATELY ECHOED, unlike the password. A TOTP code is worthless thirty
 * seconds after it is typed, and an operator who cannot see what they typed
 * will mistype it — which, under the rule below, costs them the whole
 * enrolment and a re-run.
 */
function readLineFromTty(promptText: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: true,
    });
    rl.question(promptText, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

/**
 * The one-time disclosure, and the proof that it landed.
 *
 * THE URI IS SHOWN HERE RATHER THAN AT THE END, because the end is now
 * conditional on this having worked. `bootstrapProductionOwner` does not
 * enable MFA until the code this returns verifies against the seed it just
 * sealed, so the operator's authenticator — not the script — is what decides
 * the account is usable.
 */
function showEnrolmentAndReadCode(
  log: (line: string) => void,
): (challenge: EnrolmentChallenge) => Promise<string> {
  return async ({ otpauthUri }) => {
    log('');
    log('  ── SHOWN ONCE. Scan this NOW. ───────────────────────────────────────');
    log(`  otpauth URI : ${otpauthUri}`);
    log('  ─────────────────────────────────────────────────────────────────────');
    log('  Add it to your authenticator, then type the six-digit code it shows.');
    log('  MFA is NOT enabled, and no recovery codes exist, until that code verifies.');
    log('');
    return (await readLineFromTty('  Current 6-digit code: ')).trim();
  };
}

/**
 * Where the password comes from.
 *
 * THE TERMINAL IS THE ONLY GOOD ANSWER. A typed password exists in the
 * operator's head and in this process; an exported one exists in the shell's
 * history, in `/proc`, and in whatever captured the session.
 *
 * `BOOTSTRAP_PLATFORM_OWNER_PASSWORD` is supported for the case where a
 * terminal genuinely cannot prompt, and it is deliberately PROCESS-LOCAL: it is
 * meant to be set inline for one command, never added to Railway's variables,
 * where it would sit readable by anybody with project access for as long as
 * nobody thought to remove it. The banner says so every time it is used.
 */
async function resolvePassword(log: (line: string) => void): Promise<string> {
  const fromEnvironment = process.env['BOOTSTRAP_PLATFORM_OWNER_PASSWORD'];
  if (fromEnvironment !== undefined && fromEnvironment !== '') {
    log('  Password taken from BOOTSTRAP_PLATFORM_OWNER_PASSWORD (process-local).');
    log('  If that variable is stored in Railway rather than typed inline, REMOVE IT NOW.');
    return fromEnvironment;
  }

  const first = await readSecretFromTty('  New Platform Owner password (not echoed): ');
  const second = await readSecretFromTty('  Confirm it: ');
  if (first !== second) {
    throw new BootstrapRefusal('The two passwords did not match. Nothing was written.');
  }
  return first;
}

function client(): PrismaClient {
  /*
   * THE PLATFORM ROLE, and only it. The permission catalogue, the system roles
   * and `platform_user` are platform-owned tables that the tenant role has no
   * privilege on — and `FORCE ROW LEVEL SECURITY` means even the schema owner
   * is subject to policy. This command gets no private door.
   */
  const connectionString = process.env['DATABASE_PLATFORM_URL'];
  /* c8 ignore next -- the guard already refused an absent value. */
  if (!connectionString) throw new BootstrapRefusal('DATABASE_PLATFORM_URL is not set.');
  return new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
}

async function main(): Promise<void> {
  const log = (line: string): void => console.log(line);

  // Order matters: environment first, so a wrong deployment is refused before a
  // password is ever requested; TTY second, so an operator in a pipe is stopped
  // before the enrolment that could not be shown to them is generated.
  const { ownerEmail } = assertBootstrapEnvironment(process.env);
  /*
   * THE VAULT, BEFORE THE TERMINAL. Sealing the seed is the step that cannot be
   * undone halfway, so its precondition is checked before anything else is even
   * asked for.
   */
  assertVaultCanSeal(process.env);
  assertInteractiveDisclosure(process.stdout.isTTY === true, process.stdin.isTTY === true);

  log('BrandSpace — production Platform Owner bootstrap');
  log(`  Owner address: ${ownerEmail}`);
  log('  This creates NO workspace, brand, customer or sample data.');
  log('');

  const password = await resolvePassword(log);
  const prisma = client();

  try {
    const { outcome, recoveryCodes } = await bootstrapProductionOwner({
      prisma,
      ownerEmail,
      password,
      log,
      confirmEnrolment: showEnrolmentAndReadCode(log),
    });

    log('');
    if (outcome.kind === 'already-bootstrapped') {
      log('✔ Already bootstrapped. No row was created, changed or replaced.');
      return;
    }
    if (outcome.kind === 'completed-partial') {
      log('✔ Platform Owner completed. The existing MFA enrolment was not touched.');
      return;
    }
    log(
      outcome.kind === 'resumed'
        ? '✔ Enrolment resumed and completed.'
        : '✔ Platform Owner created and enrolled.',
    );

    if (recoveryCodes) {
      /*
       * THE SECOND HALF OF THE ONE-TIME DISCLOSURE. The otpauth URI was shown
       * before the code was asked for, because the code is what proves it
       * landed; these exist only because that proof succeeded.
       */
      log('');
      log('  ── SHOWN ONCE. Nothing below can be recovered. ──────────────────────');
      log(`  recovery codes : ${recoveryCodes.join(' ')}`);
      log('  ─────────────────────────────────────────────────────────────────────');
      log('  Store them in a password manager — they are the only way back in if the');
      log('  authenticator is lost. Then clear this terminal’s scrollback.');
    }
  } finally {
    await prisma.$disconnect();
  }
}

/*
 * RUN ONLY WHEN EXECUTED DIRECTLY. The tests import `bootstrapProductionOwner`
 * and the guards; importing this module must not start prompting for a
 * password on a test runner's stdin.
 */
const executedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]).startsWith(path.resolve(import.meta.dirname));

if (executedDirectly) {
  main().catch((error: unknown) => {
    // The message, never the stack: a stack from this file names arguments.
    const message = error instanceof Error ? error.message : 'Bootstrap failed.';
    console.error(`\n✖ ${message}`);
    process.exitCode = 1;
  });
}
